Matrix.C File Reference
Various matrix operations.
#include <iostream>
#include <numC/Matrix.h>
Functions
double ** sum (double **mat1, double **mat2, int a, int b)
Elementwise summation.
double ** sub (double **mat1, double **mat2, int a, int b)
Elementwise subtraction.
double ** matmul (double **mat1, double **mat2, int a, int b, int c)
Matrix multiplication.
double ** transpose (double **mat, int a, int b)
Matrix transpose.
double ** identity (int a, double val)
Identity matrix.
double ** mat_copy (double **mat, int a, int b)
Hard copy matrix.
double ** inverse (double **A, int a, int b)
Matrix left inverse.
double ** zero (int a, int b)
Initialize matrix.
void print (double **A, int a, int b)
Print matrix.
Detailed Description
Various matrix operations.
Date
Mar 19, 2021
Author
C J Park
 chanjure@snu.ac.kr
Function Documentation
identity()
double** identity (int , double val = 1.)
Identity matrix.
create identity matrix of given size square matrix will be created
Parameters:
Parameters
a (int) dimension of identity matrix
val (double) value to initalize (default = 1.)
Returns:
Returns
result (double**) identity matrix
Example:
A = identity(3, 0.5);
Tag: identity initalize
Definition at line 88 of file Matrix.C.
Referenced by inverse().
                                    {
    static double** result;
    result = new double*[a];
    for(int i=0;i<a;i++) *(result+i) = new double [a];
    for(int i=0;i<a;i++){
        for(int j=0;j<a;j++){
            if(i==j) *(*(result+i)+j) = val;
            else *(*(result+i)+j) = 0.;
        }
    }
    return result;
}
inverse()
double** inverse (double ** , int , int)
Matrix left inverse.
Matrix left inverse using Gaussian reduction
Parameters:
Parameters
A (double**) matrix to inverse
a (int) number of rows of A
b (int) number of columns of A
Returns:
Returns
result (double**) left inverse of A
Example:
A_inv = inverse(A,2,2);
Tag: left inverse gaussian reduction
Definition at line 117 of file Matrix.C.
References identity(), mat_copy(), matmul(), print(), and transpose().
                                          {
    static double** result; // output matmul(invsqA, A.T)
    double** sqA; // squarized matrix = matmul(A.transpose, A)
    double** invsqA; // inverse of squared A
    double** A_t; // Transposed matrix
    double* row; // Temporary row container
    double* invrow; // Temporary row container for inverse matrix - memorize sort order
    double det; // determinant
    double pivot;
    const double tol = 1e-14;
    result = new double*[b];
    for(int i=0;i<b;i++) *(result+i) = new double [a];
    sqA = new double*[b];
    for(int i=0;i<b;i++) *(sqA+i) = new double [b];
    invsqA = new double*[b];
    for(int i=0;i<b;i++) *(invsqA+i) = new double [b];
    row = new double [b];
    // Initially identity matrix for inverse matrix container.
    invsqA = identity(b);
        
    // Initialize transposed matrix.
    A_t = new double*[b];
    for(int i=0; i<b;i++) *(A_t+i) = new double [b];
    
    if(a!=b){
        A_t = transpose(A,a,b);
        // Squarize the matrix
        for(int i=0;i<b;i++){
            for(int j=0;j<b;j++){
                for(int k=0;k<a;k++){
                    *(*(sqA+i)+j) = *(*(A_t+i)+k) * *(*(A+k)+j);
                }
            }
        }
    }
    else{
        A_t = identity(a);
        sqA = mat_copy(A,a,a);
    }
    // Sort pivot
    for(int j=0;j<b;j++){
        int i = 1;
        while(*(*(sqA+j)+j) <=tol && i<b){
            // Save zero pivot row
            row = *(sqA+j);
            invrow = *(invsqA+j);
            
            // Exchange with row below
            *(sqA+j) = *(sqA+j+i);
            *(invsqA+j) = *(invsqA+j+i);
            *(sqA+j+i) = row;
            *(invsqA+j+i) = invrow;
            i++;
        }
    }
    print(sqA,3,3);
    // Gauss Jordan method
    for(int i=0;i<b;i++){
        // Scale
        pivot = *(*(sqA+i)+i);
        printf("pivot : %f\n",pivot);
        if(pivot!=1.){
            for(int j=0;j<b;j++){
                *(*(invsqA+i)+j)/=pivot;
                *(*(sqA+i)+j)/=pivot;
            }
        }
        // Subtraction
        for(int j=0;j<b;j++){
            if(j!=i){
                double target = *(*(sqA+j)+i);
                for(int k=0;k<b;k++){
                    *(*(invsqA+j)+k) -= *(*(invsqA+i)+k) * target;
                    *(*(sqA+j)+k) -= *(*(sqA+i)+k) * target;
                }
            }
        }
    }
    result = matmul(invsqA, A_t, b,b,a);
    return result;
}
mat_copy()
double** mat_copy (double ** , int , int)
Hard copy matrix.
create hard copy of given matrix
Parameters:
Parameters
mat (double**) matrix to copy
a (int) number of rows of mat
b (int) number of columns of mat
Returns:
Returns
result (double**) hard copy of mat
Example:
A = mat_copy(B,3,3);
Tag: ftn
Definition at line 104 of file Matrix.C.
Referenced by inverse().
                                             {
    static double** result;
    result = new double*[a];
    for(int i=0;i<a;i++) *(result+i) = new double [b];
    for(int i=0;i<a;i++){
        for(int j=0;j<b;j++) *(*(result+i)+j) = *(*(mat+i)+j);
    }
    return result;
}
matmul()
double** matmul (double ** , double ** , int , int , int)
Matrix multiplication.
mat1 * mat2 = result number of column of mat1 must match number of column of mat2
Parameters:
Parameters
mat1,mat2 (double**) matrices to be multiplied
a (int) number of rows of mat1
b (int) number of folumns of mat1 = number of rows of mat2
c (int) number of columns of mat2
Returns:
Returns
result (double**) matrix of dimension a x c
Example:
A = matmul(A,B,2,3,2);
Tag: multiplication
Definition at line 45 of file Matrix.C.
Referenced by inverse().
                                                                  {
    
    static double** result;
    
    result = new double*[a];
    for(int i=0;i<a;i++) *(result + i) = new double [c];
    for(int i=0;i<a;i++){
        for(int j=0;j<c;j++) *(*(result+i)+j) = 0.;
    }
    for(int i=0;i<a;i++){
        for(int j=0;j<c;j++){
            for(int k=0;k<b;k++){
                *(*(result+i)+j) += *(*(mat1+i)+k) * *(*(mat2+k)+j);
            }
        }
    }
    return result;
}
print()
void print (double ** , int , int)
Print matrix.
print matrix of given size
Parameters:
Parameters
A (double**) matrix to print
a (int) number of rows of A
b (int) number of columns of A
Returns:
Returns
stdout(matrix A)
Example:
print(A,2,3);
Tag: print
Definition at line 225 of file Matrix.C.
Referenced by inverse().
                                    {
    for(int i=0;i<a;i++){
        for(int j=0;j<b;j++) printf("%10.4e ", *(*(A+i)+j));
        printf("\n");
    }
}
sub()
double** sub (double ** , double ** , int , int)
Elementwise subtraction.
mat1 - mat2 = result Two input matrices must be in same shape axb
Parameters:
Parameters
mat1,mat2 (double**) matrices to be subtracted
a (int) number of rows of mat1 and mat2
b (int) number of columns of mat1 and mat2
Returns:
Returns
result (double**)
Example:
A = sub(A,B,2,2);
Tag: subtract, element wise
Definition at line 31 of file Matrix.C.
                                                        {
    
    static double** result;
    result = new double*[a];
    for(int i=0;i<a;i++) *(result+i) = new double [b];
    for(int i=0;i<a;i++){
        for(int j=0;j<b;j++) *(*(result+i)+j) = *(*(mat1+i)+j) - *(*(mat2+i)+j);
    }
    return result;
}
sum()
double** sum (double ** , double ** , int , int)
Elementwise summation.
mat1 + mat2 = result Two input matrices must be in same shape axb
Parameters:
Parameters
mat1,mat2 (double**) matrices to be added
a (int) number of rows of mat1 and mat2
b (int) number of columns of mat1 and mat2
Returns:
Returns
result (double**)
Example:
A = sum(A,B,2,2);
Tag: add, sum, element wise
Definition at line 17 of file Matrix.C.
                                                        {
    
    static double** result;
    result = new double*[a];
    for(int i=0;i<a;i++) *(result+i) = new double [b];
    for(int i=0;i<a;i++){
        for(int j=0;j<b;j++) *(*(result+i)+j) = *(*(mat1+i)+j) + *(*(mat2+i)+j);
    }
    return result;
}
transpose()
double** transpose (double ** , int , int)
Matrix transpose.
mat^T
Parameters:
Parameters
mat (double**) matrix to be transposed
a (int) number of rows of mat
b (int) number of columns of mat
Returns:
Returns
result (double**) transposed mat
Example:
A_T = transpose(A,2,2);
Tag: transpose
Definition at line 67 of file Matrix.C.
Referenced by inverse().
                                              {
    static double** result;
    result = new double*[b];
    for(int i=0;i<b;i++) *(result+i) = new double [a];
    for(int i=0;i<a;i++){
        for(int j=0;j<b;j++){
            *(*(result+j)+i) = *(*(mat+i)+j);
        }
    }
    return result;
}
zero()
double** zero (int , int)
Initialize matrix.
Create and initialize matrix elements to zero
Parameters:
Parameters
a (int) number of rows
b (int) number of columns
Returns:
Returns
result (double**) zero matrix of size axb
Example:
A = zero(2,3);
Tag: initalize zero
Definition at line 212 of file Matrix.C.
                           {
    static double** result;
    
    result = new double*[a];
    for(int i=0;i<a;i++) *(result+i) = new double [b];
    for(int i=0;i<a;i++){
        for(int j=0;j<b;j++) *(*(result+i)+j) = 0.;
    }
    
    return result;
}