Stats.C File Reference
Statistics tools.
#include <math.h>
#include <numC/Matrix_gsl.h>
#include <numC/Stats.h>
#include <iostream>
Functions
Matrix ave (Matrix A, int axis)
Matrix average.
Matrix var (Matrix A, int axis)
Matrix variance.
Matrix cov (Matrix A, int axis)
Covariance matrix.
Matrix * JK_resample (Matrix A, int axis)
Jackknife resample.
Matrix sample_ave (Matrix *A, int l)
Sample average.
Matrix JK_error (Matrix *A, int l)
Jackknife standard deviation.
Matrix BS_error (Matrix *A, int l)
Bootstrap standard deviation.
double chisqr (Matrix y_bar, Matrix c_inv, Matrix f)
Chi square.
Detailed Description
Statistics tools.
Function Documentation
ave()
Matrix ave (Matrix A, int axis = 1)
Matrix average.
Calculate average along the given axis
Parameters:
Parameters
A (Matrix) Matrix to calculate
axis (int) axis to calculate default = 1
Returns:
Returns
result (Matrix) a vector (collapsed Matrix)
Example:
B = ave(A, 0);
Tag: average vector matrix
Definition at line 13 of file Stats.C.
Referenced by cov(), and var().
                              {
  
  int n = A.shape[0];
  int m = A.shape[1];
  if(axis == 1){
    Matrix result(n,1,"ave");
    for(int i=0;i<n;i++){
      for(int j=0;j<m;j++){
        result.matrix[i][0] += A.matrix[i][j]/(1.*m);
      }
    }
    
    return result;
  }
  else if (axis == 0){
    
    Matrix result(1,m);
    
    for(int i=0;i<n;i++){
      for(int j=0;j<m;j++) result.matrix[0][j] += A.matrix[i][j]/(1.*n);
    }
    return result;
  }
}
BS_error()
Matrix BS_error (Matrix * A, int l)
Bootstrap standard deviation.
Calculate standard deviation(sqrt(var), error) of Bootstrap resampled data
Parameters:
Parameters
A (Matrix*) Bootstrap resampled data
l (int) number of BS samples
Returns:
Returns
result (Martix) collapsed array of Matrices
Example:
A = BS_error(B, 500);
Tag: Bootstrap standard deviation error
Definition at line 163 of file Stats.C.
References sample_ave().
                                 {
  int n = A[0].shape[0];
  
  Matrix A_ave(n,1);
  A_ave = sample_ave(A, l);
  Matrix result(n,1);
  for(int i=0;i<n;i++){
    for(int j=0;j<l;j++) result.matrix[i][0] += pow(A[j].matrix[i][0] - A_ave.matrix[i][0],2.) / (l-1.);
  }
  for(int i=0;i<n;i++) result.matrix[i][0] = sqrt(result.matrix[i][0]);
  return result;
}
chisqr()
double chisqr (Matrix y_bar, Matrix c_inv, Matrix f)
Chi square.
Calculate chi-square of given data chi^2 = (y_bar - f)^T C^-1 (y_bar - f)
Parameters:
Parameters
y_bar (Matrix) vector containing an average of the data
c_inv (Matrix) inverse of covariance matrix
f (Matrix) vector of fitting function values
Returns:
Returns
result (double) chi^2 of given data and fitting function
Example:
chisq = chiqr(Y_bar, C_inv, F);
Tag: chi-square fitting
Definition at line 180 of file Stats.C.
References matmul(), and sub().
                                                   {
  double result;
  result = matmul(matmul(sub(y_bar, f).T(), c_inv), sub(y_bar, f)).matrix[0][0];
  return result;
}
cov()
Matrix cov (Matrix A, int axis = 0)
Covariance matrix.
Calculate covariance along the given axis
Parameters:
Parameters
A (Matrix) Matrix of data
axis (int) axis to calculate default = 0
Returns:
Returns
result (Matrix) covariance of vectors along axis
Example:
C = cov(A, 0);
Tag: covariance vector matrix
Definition at line 70 of file Stats.C.
References ave().
                              {
  // Default : sample covariance
  int n = A.shape[0];
  int m = A.shape[1];
  
  if(axis == 0){
    Matrix A_ave;
    A_ave = ave(A, 1);
    Matrix result(n,n);
    for(int i=0;i<n;i++){
      for(int j=0;j<n;j++){
        for(int k=0;k<m;k++){
          result.matrix[i][j] += (A.matrix[i][k] - A_ave.matrix[i][0]) * (A.matrix[j][k] - A_ave.matrix[j][
      0])/(1.*m)/(m-1.);
        }
      }
    }
    return result;
  }
  else if(axis == 1){
    Matrix A_ave = ave(A, 0);
    Matrix result(m,m);
    for(int i=0;i<m;i++){
      for(int j=0;j<m;j++){
        for(int k=0;k<n;k++) result.matrix[i][j] += (A.matrix[k][i] - A_ave.matrix[0][i]) * (A.matrix[k][j]
       - A_ave.matrix[0][j])/(1.*m)/(m-1.);
      }
    }
    return result;
  }
}
JK_error()
Matrix JK_error (Matrix * A, int l)
Jackknife standard deviation.
Calculate standard deviation(sqrt(var), error) of Jackknife resampled data
Parameters:
Parameters
A (Matrix*) Jackknife resampled data
l (int) number of JK samples (N)
Returns:
Returns
result (Matrix) collapsed array of Matrices
Example:
A = JK_error(B, 200);
Tag: Jackknife standard deviation error
Definition at line 145 of file Stats.C.
References sample_ave().
                                 {
  int n = A[0].shape[0];
  
  Matrix A_ave(n,1);
  A_ave = sample_ave(A, l);
  Matrix result(n, 1);
  for(int i=0;i<n;i++){
    for(int j=0;j<l;j++) result.matrix[i][0] += pow(A[j].matrix[i][0] - A_ave.matrix[i][0], 2.) /(1.*l)*(l-
      1.);
  }
  for(int i=0;i<n;i++) result.matrix[i][0] = sqrt(result.matrix[i][0]);
  return result;
}
JK_resample()
Matrix* JK_resample (Matrix A, int axis = 1)
Jackknife resample.
Resample along the given axis It samples maximum amount of data (N samples)
Parameters:
Parameters
A (Matrix) Matrix of data
axis (int) axis to calculate default = 1
Returns:
Returns
result (Matrix*) Array(Pointer) of matrix
Example:
X = JK_resample(A, 0);
Tag: Jackknife resampling
Definition at line 107 of file Stats.C.
                                       {
  
  int n = A.shape[0];
  int m = A.shape[1];
  Matrix *result;
  result = new Matrix [m];
  for(int i=0;i<m;i++) result[i].init(n, m-1);
  int p=0;
  for(int i=0;i<m;i++){
    for(int j=0;j<n;j++){
      p = 0;
      for(int k=0;k<m;k++){
        if(i != k){
          result[i].matrix[j][p] = A.matrix[j][k];
          p++;
        }
      }
    }
  }
  return result;
}
sample_ave()
Matrix sample_ave (Matrix * A, int l)
Sample average.
Calculate average of array(pointer) of Matrices
Parameters:
Parameters
A (Matrix*) Pointer to Matrix eg) resampled data
l (int) number of JK samples (N)
Returns:
Returns
result (Matrix) collapsed array of Matrices
Example:
A = sample_ave(B, 200);
Tag: Jackknife average
Definition at line 132 of file Stats.C.
Referenced by BS_error(), and JK_error().
                                   {
  int n = A[0].shape[0];
  Matrix result(n,1);
  for(int i=0;i<n;i++){
    for(int j=0;j<l;j++) result.matrix[i][0] += A[j].matrix[i][0]/(1.*l);
  }
  return result;
}
var()
Matrix var (Matrix A, int axis = 1)
Matrix variance.
Calculate variance along the given axis
Parameters:
Parameters
A (Matrix) Matrix to calculate
axis (int) axis to calculate default = 1
Returns:
Returns
result (Matrix) a vector (collapsed Matrix)
Example:
B = var(A,0);
Tag: variance vector matrix
Definition at line 42 of file Stats.C.
References ave().
                              {
  // Default : sample var
  int n = A.shape[0];
  int m = A.shape[1];
  if(axis == 1){
    Matrix A_ave = ave(A, 1);
    Matrix result(n,1);
    for(int i=0;i<n;i++){
      for(int j=0;j<m;j++) result.matrix[i][0] += pow(A.matrix[i][j] - A_ave.matrix[i][0], 2.)/(1.*m)/(m -
      1.);
    }
    return result;
  }
  else if(axis == 0){
    Matrix A_ave = ave(A, 0);
    Matrix result(1,m);
    
    for(int i=0;i<n;i++){
      for(int j=0;j<m;j++) result.matrix[0][j] += pow(A.matrix[i][j] - A_ave.matrix[0][j], 2.)/(1.*n)/(n -
      1.);
    }
    return result;
  }
}